apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: default
  labels:
    app: todo-frontend
spec:
  type: LoadBalancer
  selector:
    app: todo-frontend
  ports:
    - port: 80
      targetPort: 80
